In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import pickle

from sklearn.datasets import fetch_openml
from keras.datasets import mnist

from sklearn.ensemble import RandomForestClassifier 
from sklearn import svm

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier


from sklearn.svm import SVC

In [2]:
#les données
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)


In [3]:
#reshape des images sous forme d'un vecteur
X_train = X_train.reshape(60000,-1)
X_test = X_test.reshape(10000,-1)

Train the model on the SVC Support vector Machines 

https://www.vebuso.com/2020/03/svm-hyperparameter-tuning-using-gridsearchcv/ 

In [8]:
# train the model on train set
model = SVC()
model.fit(X_train, y_train)


SVC()

In [9]:
# get the score
scoring = model.score(X_train, y_train)
print("Training score: ", scoring) 

Training score:  0.9899166666666667


In [10]:
ypred = model.predict(X_test)

In [20]:
# score test 
model.score(X_test, y_test)

0.9792

In [11]:
classification = classification_report(y_test, ypred)
print(classification)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      0.97      0.97      1028
           8       0.97      0.98      0.97       974
           9       0.97      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



In [21]:

pickle.dump(model, open('modelSVC', 'wb'))

In [ ]:
# defining parameter range
param_grid = {'C': [1, 10, 100, 1000], 
              'gamma': [1,0.1,0.001,0.0001],
              'kernel': ['rbf',  'linear']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 2)
  
# fitting the model for grid search
grid.fit(X_train, y_train)


In [ ]:

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

In [ ]:
grid_predictions = grid.best_estimator_(X_test)
  
# print classification report
print(classification_report(y_test, grid_predictions))

In [ ]:
# SVM SVC model 
from sklearn import svm

clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X_train, y_train)
# get the score
s = clf.score(X_train, y_train)
print("Training score: ", s) 

SGD Classifier 

In [4]:
sgdc = SGDClassifier(max_iter=1000, tol=0.01)
 
sgdc.fit(X_train, y_train)

SGDClassifier(tol=0.01)

In [5]:
score = sgdc.score(X_train, y_train)
print("Training score: ", score) 


Training score:  0.8924833333333333


In [6]:
ypred = sgdc.predict(X_test)

cm = confusion_matrix(y_test, ypred)
print(cm) 

[[ 935    0    3    6    2    2    8    1   17    6]
 [   0 1034    6    3    0    1    4    1   81    5]
 [   3    1  897   16    5    2   13    9   79    7]
 [   6    0   26  832    3   28    4   14   81   16]
 [   0    1    7    4  880    1    8    3   21   57]
 [  10    2    1   32   12  720   22    5   64   24]
 [  12    1    7    1    7   24  883    1   20    2]
 [   1    1   23    4   13    1    0  903   12   70]
 [   8    3    6   18   10   21    6    4  872   26]
 [   1    2    2    6   21    7    0   15   34  921]]


In [7]:
cr = classification_report(y_test, ypred)
print(cr)

              precision    recall  f1-score   support

           0       0.96      0.95      0.96       980
           1       0.99      0.91      0.95      1135
           2       0.92      0.87      0.89      1032
           3       0.90      0.82      0.86      1010
           4       0.92      0.90      0.91       982
           5       0.89      0.81      0.85       892
           6       0.93      0.92      0.93       958
           7       0.94      0.88      0.91      1028
           8       0.68      0.90      0.77       974
           9       0.81      0.91      0.86      1009

    accuracy                           0.89     10000
   macro avg       0.90      0.89      0.89     10000
weighted avg       0.90      0.89      0.89     10000

