<a href="https://colab.research.google.com/github/75andybermond/MnistSklearnProject/blob/main/NotebookMNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import pickle

from sklearn.datasets import fetch_openml
from keras.datasets import mnist

from sklearn.ensemble import RandomForestClassifier 
from sklearn import svm

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier


from sklearn.svm import SVC

In [4]:
#les données
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)

In [5]:
#reshape des images sous forme d'un vecteur
X_train = X_train.reshape(60000,-1)
X_test = X_test.reshape(10000,-1)

Train the model on the SVC Support vector Machines 

In [10]:
# train the model on train set
model = SVC()
model.fit(X_train, y_train)


AttributeError: ignored

In [ ]:
# get the score
scoring = model.score(X_train, y_train)
print("Training score: ", scoring) 

In [ ]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ['rbf',  'sigmoid']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 2)
  
# fitting the model for grid search
grid.fit(X_train, y_train)


Fitting 5 folds for each of 32 candidates, totalling 160 fits


In [ ]:

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

In [ ]:
grid_predictions = grid.best_estimator_(X_test)
  
# print classification report
print(classification_report(y_test, grid_predictions))

SGD Classifier 

In [6]:
sgdc = SGDClassifier(max_iter=1000, tol=0.01)
 
sgdc.fit(X_train, y_train)

SGDClassifier(tol=0.01)


SGDClassifier(tol=0.01)

In [7]:
score = sgdc.score(X_train, y_train)
print("Training score: ", score) 


Training score:  0.8781666666666667


In [8]:
ypred = sgdc.predict(X_test)

cm = confusion_matrix(y_test, ypred)
print(cm) 

[[ 951    0    7    7    0    3    4    1    4    3]
 [   0 1125    3    2    0    1    3    1    0    0]
 [   3   38  856   68    6    6    7    7   35    6]
 [   3    5   18  944    0   14    1    5   11    9]
 [   4    7   11   27  845    8    6    2   18   54]
 [  12    6    4  113    2  702    2   10   36    5]
 [  10    5   15   16    4   53  852    0    3    0]
 [   2   15   23   25    2    4    1  909    3   44]
 [   8   38   19  103    8   94    4    3  679   18]
 [   5   14    6   41   13   35    0   17    8  870]]


In [9]:
cr = classification_report(y_test, ypred)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       980
           1       0.90      0.99      0.94      1135
           2       0.89      0.83      0.86      1032
           3       0.70      0.93      0.80      1010
           4       0.96      0.86      0.91       982
           5       0.76      0.79      0.77       892
           6       0.97      0.89      0.93       958
           7       0.95      0.88      0.92      1028
           8       0.85      0.70      0.77       974
           9       0.86      0.86      0.86      1009

    accuracy                           0.87     10000
   macro avg       0.88      0.87      0.87     10000
weighted avg       0.88      0.87      0.87     10000

